import struct

from forza_telemetry_analyzer.models import TelemetryData

#forza UDP Sled packet layout.
#We currently parse the fields need by telemetryData

#_PACKET_FORMAT = "<iIffffffffffffffffffffffffffffIIIIIIIIffffffffffffffffIIIIIIffffffffffffffffIIIIIIIIIIB"
_PACKET_FORMAT = "<iIfffffffffffffffffffffffffffiiiiiiiiffffffffffffffffIIIIII"
_PACKET_SIZE = struct.calcsize(_PACKET_FORMAT)

class PacketParseError(ValueError):
    """Raised when a Forza telemetry packet cannot be parsed correctly"""

def parse_packet(data: bytes) -> TelemetryData:
    """Parse a Forza telemetry packet into a TelemetryData object.

    Args:
        data (bytes): Raw telemetry packet bytes.

    Returns:
        TelemetryData: The parsed telemetry data.

    Raises:
        PacketParseError: If the packet cannot be parsed correctly.
    """
    if len(data) != _PACKET_SIZE:
        raise PacketParseError(
            f"Invalid packet size: expected {_PACKET_SIZE} bytes, "
            f"got {len(data)}"
        )
    (   
        is_race_on,
        timestamp_ms,
        engine_max_rpm,
        engine_idle_rpm,
        current_engine_rpm,
        acceleration_x,
        acceleration_y,
        acceleration_z,
        velocity_x,
        velocity_y,
        velocity_z,
        angular_velocity_x,
        angular_velocity_y,
        angular_velocity_z,
        yaw,
        pitch,
        roll,
        normalized_suspension_travel_front_left,
        normalized_suspension_travel_front_right,
        normalized_suspension_travel_rear_left,
        normalized_suspension_travel_rear_right,
        tire_slip_ratio_front_left,
        tire_slip_ratio_front_right,
        tire_slip_ratio_rear_left,
        tire_slip_ratio_rear_right,
        wheel_rotation_speed_front_left,
        wheel_rotation_speed_front_right,
        wheel_rotation_speed_rear_left,
        wheel_rotation_speed_rear_right,
        wheel_on_rumble_strip_front_left,
        wheel_on_rumble_strip_front_right,
        wheel_on_rumble_strip_rear_left,
        wheel_on_rumble_strip_rear_right,
        wheel_in_puddle_front_left,
        wheel_in_puddle_front_right,
        wheel_in_puddle_rear_left,
        wheel_in_puddle_rear_right,
        surface_rumble_front_left,
        surface_rumble_front_right,
        surface_rumble_rear_left,
        surface_rumble_rear_right,
        tire_slip_angle_front_left,
        tire_slip_angle_front_right,
        tire_slip_angle_rear_left,
        tire_slip_angle_rear_right,
        tire_combined_slip_front_left,
        tire_combined_slip_front_right,
        tire_combined_slip_rear_left,
        tire_combined_slip_rear_right,
        suspension_travel_meters_front_left,
        suspension_travel_meters_front_right,
        suspension_travel_meters_rear_left,
        suspension_travel_meters_rear_right,
        car_ordinal,
        car_class,
        car_performance_index,
        drivetrain_type,
        num_cylinders,
        car_group,
#        smashable_vel_diff,
#        smashable_mass,
#        position_x,
#        position_y,
#        position_z,
#        speed,
#        power,
#        torque,
#        tire_temp_front_left,
#        tire_temp_front_right,
#        tire_temp_rear_left,
#        tire_temp_rear_right,
#        boost,
#        fuel,
#        distance_traveled,
#        best_lap,
#        last_lap,
#        current_lap,
#        current_race_time,
#        lap_number,
#        race_position,
#        accel,
#        brake,
#        clutch,
#        hand_brake,
#        gear,
#        steer,
#        normalized_driving_line,
#        normalized_ai_brake_difference,
    ) = struct.unpack(_PACKET_FORMAT, data)

    return TelemetryData(
        is_race_on = is_race_on,
        timestamp_ms = timestamp_ms,
        engine_max_rpm = engine_max_rpm,
        engine_idle_rpm = engine_idle_rpm,
        current_engine_rpm = current_engine_rpm,
        acceleration_x = acceleration_x,
        acceleration_y = acceleration_y,
        acceleration_z = acceleration_z,
        velocity_x = velocity_x,
        velocity_y = velocity_y, 
        velocity_z = velocity_z,
        angular_velocity_x = angular_velocity_x,
        angular_velocity_y = angular_velocity_y,
        angular_velocity_z = angular_velocity_z,
        yaw = yaw,
        pitch = pitch,
        roll = roll,
        normalized_suspension_travel_front_left = normalized_suspension_travel_front_left,
        normalized_suspension_travel_front_right = normalized_suspension_travel_front_right,
        normalized_suspension_travel_rear_left = normalized_suspension_travel_rear_left,
        normalized_suspension_travel_rear_right = normalized_suspension_travel_rear_right,
        tire_slip_ratio_front_left = tire_slip_ratio_front_left,
        tire_slip_ratio_front_right = tire_slip_ratio_front_right,
        tire_slip_ratio_rear_left = tire_slip_ratio_rear_left,
        tire_slip_ratio_rear_right = tire_slip_ratio_rear_right,
        wheel_rotation_speed_front_left = wheel_rotation_speed_front_left,
        wheel_rotation_speed_front_right = wheel_rotation_speed_front_right,
        wheel_rotation_speed_rear_left = wheel_rotation_speed_rear_left,
        wheel_rotation_speed_rear_right = wheel_rotation_speed_rear_right,
        wheel_on_rumble_strip_front_left = wheel_on_rumble_strip_front_left,
        wheel_on_rumble_strip_front_right = wheel_on_rumble_strip_front_right,
        wheel_on_rumble_strip_rear_left = wheel_on_rumble_strip_rear_left,
        wheel_on_rumble_strip_rear_right = wheel_on_rumble_strip_rear_right,
        wheel_in_puddle_front_left = wheel_in_puddle_front_left,
        wheel_in_puddle_front_right = wheel_in_puddle_front_right,
        wheel_in_puddle_rear_left = wheel_in_puddle_rear_left,
        wheel_in_puddle_rear_right = wheel_in_puddle_rear_right,
        surface_rumble_front_left = surface_rumble_front_left,
        surface_rumble_front_right = surface_rumble_front_right,
        surface_rumble_rear_left = surface_rumble_rear_left,
        surface_rumble_rear_right = surface_rumble_rear_right,
        tire_slip_angle_front_left = tire_slip_angle_front_left,
        tire_slip_angle_front_right = tire_slip_angle_front_right,
        tire_slip_angle_rear_left = tire_slip_angle_rear_left,
        tire_slip_angle_rear_right = tire_slip_angle_rear_right,
        tire_combined_slip_front_left = tire_combined_slip_front_left,
        tire_combined_slip_front_right = tire_combined_slip_front_right,
        tire_combined_slip_rear_left = tire_combined_slip_rear_left,
        tire_combined_slip_rear_right = tire_combined_slip_rear_right,
        suspension_travel_meters_front_left = suspension_travel_meters_front_left,
        suspension_travel_meters_front_right = suspension_travel_meters_front_right,
        suspension_travel_meters_rear_left = suspension_travel_meters_rear_left,
        suspension_travel_meters_rear_right = suspension_travel_meters_rear_right,
        car_ordinal = car_ordinal,
        car_class = car_class,
        car_performance_index = car_performance_index,
        drivetrain_type = drivetrain_type,
        num_cylinders = num_cylinders,
        car_group = car_group,
#        smashable_vel_diff = smashable_vel_diff,
#        smashable_mass = smashable_mass,
#        position_x = position_x,
#        position_y = position_y,
#        position_z = position_z,
#        speed = speed,
#        power = power,
#        torque = torque,
#        tire_temp_front_left = tire_temp_front_left,
#        tire_temp_front_right = tire_temp_front_right,
#        tire_temp_rear_left = tire_temp_rear_left,
#        tire_temp_rear_right = tire_temp_rear_right,
#        boost = boost,
#        fuel = fuel,
#        distance_traveled = distance_traveled,
#        best_lap = best_lap,
#        last_lap = last_lap,
#        current_lap = current_lap,
#        current_race_time = current_race_rpm,
#        lap_number = lap_number,
#        race_position = race_position,
#        accel = accel,
#        brake = brake,
#        clutch = clutch,
#        hand_brake = hand_brake,
#        gear = gear,
#        steer = steer,
#        normalized_driving_line = normalized_driving_line,
#        normalized_ai_brake_difference = normalized_ai_brake_difference,
    )
  