import csv
from pathlib import Path

from forza_telemetry_analyzer.models import TelemetryData

FIELD_NAMES = [
    "is_race_on",
    "timestamp_ms",
    "engine_max_rpm",
    "engine_idle_rpm",
    "current_engine_rpm",
    "acceleration_x",
    "acceleration_y",
    "acceleration_z",
    "velocity_x",
    "velocity_y",
    "velocity_z",
    "angular_velocity_x",
    "angular_velocity_y",
    "angular_velocity_z",
    "yaw",
    "pitch",
    "roll",
    "normalized_suspension_travel_front_left",
    "normalized_suspension_travel_front_right",
    "normalized_suspension_travel_rear_left",
    "normalized_suspension_travel_rear_right",
    "tire_slip_ratio_front_left",
    "tire_slip_ratio_front_right",
    "tire_slip_ratio_rear_left",
    "tire_slip_ratio_rear_right",
    "wheel_rotation_speed_front_left",
    "wheel_rotation_speed_front_right",
    "wheel_rotation_speed_rear_left",
    "wheel_rotation_speed_rear_right",
    "wheel_on_rumble_strip_front_left",
    "wheel_on_rumble_strip_front_right",
    "wheel_on_rumble_strip_rear_left",
    "wheel_on_rumble_strip_rear_right",
    "wheel_in_puddle_front_left",
    "wheel_in_puddle_front_right",
    "wheel_in_puddle_rear_left",
    "wheel_in_puddle_rear_right",
    "surface_rumble_front_left",
    "surface_rumble_front_right",
    "surface_rumble_rear_left",
    "surface_rumble_rear_right",
    "tire_slip_angle_front_left",
    "tire_slip_angle_front_right",
    "tire_slip_angle_rear_left",
    "tire_slip_angle_rear_right",
    "tire_combined_slip_front_left",
    "tire_combined_slip_front_right",
    "tire_combined_slip_rear_left",
    "tire_combined_slip_rear_right",
    "suspension_travel_meters_front_left",
    "suspension_travel_meters_front_right",
    "suspension_travel_meters_rear_left",
    "suspension_travel_meters_rear_right",
    "car_ordinal",
    "car_class",
    "car_performance_index",
    "drivetrain_type",
    "num_cylinders",
    "car_group",
    "smashable_vel_diff",
    "smashable_mass",
    "position_x",
    "position_y",
    "position_z",
    "speed",
    "power",
    "torque",
    "tire_temp_front_left",
    "tire_temp_front_right",
    "tire_temp_rear_left",
    "tire_temp_rear_right",
    "boost",
    "fuel",
    "distance_traveled",
    "best_lap",
    "last_lap",
    "current_lap",
    "current_race_time",
    "lap_number",
    "race_position",
    "accel",
    "brake",
    "clutch",
    "hand_brake",
    "gear",
    "steer",
    "normalized_driving_line",
    "normalized_ai_brake_difference",
]


def write_telemetry(
    file_path: Path,
    telemetry: TelemetryData,
) -> None:
    file_exists = file_path.exists()

    with file_path.open("a", newline="") as file:
        writer = csv.DictWriter(
            file,
            fieldnames=FIELD_NAMES,
            extrasaction="ignore",
        )

        if not file_exists or file_path.stat().st_size == 0:
            writer.writeheader()

        writer.writerow(vars(telemetry))
